import XCTest
@testable import PelicanCon

// MARK: - SurveyQuestionType tests

final class SurveyQuestionTypeTests: XCTestCase {

    func testRawValues() {
        XCTAssertEqual(SurveyQuestionType.text.rawValue,        "text")
        XCTAssertEqual(SurveyQuestionType.multiChoice.rawValue, "multiChoice")
    }

    func testCodableRoundtrip() throws {
        for qType in [SurveyQuestionType.text, .multiChoice] {
            let data    = try JSONEncoder().encode(qType)
            let decoded = try JSONDecoder().decode(SurveyQuestionType.self, from: data)
            XCTAssertEqual(decoded, qType)
        }
    }
}

// MARK: - SurveyQuestion tests

final class SurveyQuestionTests: XCTestCase {

    func testAutoGeneratedIdIsUUID() {
        let q = SurveyQuestion(
            prompt: "What was your favourite class?",
            type: .text,
            options: [],
            order: 0
        )
        XCTAssertNotNil(UUID(uuidString: q.id))
    }

    func testTwoQuestionsHaveDifferentIds() {
        let q1 = SurveyQuestion(prompt: "Q1", type: .text, options: [], order: 0)
        let q2 = SurveyQuestion(prompt: "Q2", type: .text, options: [], order: 1)
        XCTAssertNotEqual(q1.id, q2.id)
    }

    func testTextQuestionHasEmptyOptions() {
        let q = SurveyQuestion(prompt: "Describe your experience", type: .text, options: [], order: 0)
        XCTAssertTrue(q.options.isEmpty)
    }

    func testMultiChoiceQuestionStoresOptions() {
        let opts = ["Once a year", "Several times", "This is my first time"]
        let q = SurveyQuestion(prompt: "How often do you attend reunions?", type: .multiChoice, options: opts, order: 2)
        XCTAssertEqual(q.options, opts)
        XCTAssertEqual(q.options.count, 3)
    }

    func testFieldsStoredCorrectly() {
        let q = SurveyQuestion(
            prompt: "What do you remember most about school?",
            type: .multiChoice,
            options: ["Sports", "Classes", "Friends", "Mischief"],
            order: 5
        )
        XCTAssertEqual(q.prompt, "What do you remember most about school?")
        XCTAssertEqual(q.type, .multiChoice)
        XCTAssertEqual(q.order, 5)
        XCTAssertEqual(q.options.count, 4)
    }

    func testCodableRoundtrip() throws {
        let original = SurveyQuestion(
            prompt: "Favourite memory?",
            type: .text,
            options: [],
            order: 1
        )
        let data    = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(SurveyQuestion.self, from: data)
        XCTAssertEqual(decoded.id,     original.id)
        XCTAssertEqual(decoded.prompt, original.prompt)
        XCTAssertEqual(decoded.type,   original.type)
        XCTAssertEqual(decoded.order,  original.order)
    }
}

// MARK: - SurveyResponse tests

final class SurveyResponseTests: XCTestCase {

    func testAnswersDictionaryRetrieval() {
        let qId1 = UUID().uuidString
        let qId2 = UUID().uuidString
        let response = SurveyResponse(
            id: nil,
            userId: "user-1",
            displayName: "Alice",
            submittedAt: Date(),
            answers: [qId1: "Sports", qId2: "Friends"]
        )
        XCTAssertEqual(response.answers[qId1], "Sports")
        XCTAssertEqual(response.answers[qId2], "Friends")
    }

    func testMissingAnswerKeyReturnsNil() {
        let response = SurveyResponse(
            id: nil,
            userId: "user-1",
            displayName: "Alice",
            submittedAt: Date(),
            answers: [:]
        )
        XCTAssertNil(response.answers["non-existent-id"])
    }

    func testFieldsStoredCorrectly() {
        let date = Date()
        let response = SurveyResponse(
            id: "resp-42",
            userId: "user-99",
            displayName: "Carol",
            submittedAt: date,
            answers: ["q1": "answer1"]
        )
        XCTAssertEqual(response.id, "resp-42")
        XCTAssertEqual(response.userId, "user-99")
        XCTAssertEqual(response.displayName, "Carol")
        XCTAssertEqual(response.submittedAt, date)
    }

    func testCodableRoundtrip() throws {
        let qId = UUID().uuidString
        let original = SurveyResponse(
            id: nil,
            userId: "user-1",
            displayName: "Alice",
            submittedAt: Date(timeIntervalSince1970: 1_000_000),
            answers: [qId: "My answer"]
        )

        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .secondsSince1970
        let data = try encoder.encode(original)

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .secondsSince1970
        let decoded = try decoder.decode(SurveyResponse.self, from: data)

        XCTAssertEqual(decoded.userId, original.userId)
        XCTAssertEqual(decoded.displayName, original.displayName)
        XCTAssertEqual(decoded.answers[qId], "My answer")
        XCTAssertEqual(decoded.submittedAt.timeIntervalSince1970,
                       original.submittedAt.timeIntervalSince1970,
                       accuracy: 1.0)
    }
}
